"""Generate RSA keypair + signed JWTs as Zig const arrays for auth.zig tests."""
import jwt, json, base64
from cryptography.hazmat.primitives.asymmetric import rsa

KID = "test-kid-1"
ISS = "test-iss"
NOW = 1_700_000_000

key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
pub_numbers = key.public_key().public_numbers()
modulus = pub_numbers.n.to_bytes((pub_numbers.n.bit_length() + 7) // 8, "big")
exponent = pub_numbers.e.to_bytes((pub_numbers.e.bit_length() + 7) // 8, "big")

def b64url(b):
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()

def sign(payload, headers=None):
    h = {"alg": "RS256", "typ": "JWT", "kid": KID}
    if headers:
        h.update(headers)
    return jwt.encode(payload, key, algorithm="RS256", headers=h)

def make_hs256_header_token(payload):
    # Hand-built token with alg=HS256 in the header. Signature is junk; we
    # only need the verifier to reject on UnsupportedAlgorithm before the
    # signature check runs.
    h = {"alg": "HS256", "typ": "JWT", "kid": KID}
    head = b64url(json.dumps(h, separators=(",", ":")).encode())
    body = b64url(json.dumps(payload, separators=(",", ":")).encode())
    sig = b64url(b"\x00" * 32)
    return f"{head}.{body}.{sig}"

def bytes_to_zig(b):
    return "&.{ " + ", ".join(f"0x{x:02x}" for x in b) + " }"

valid = {"iss": ISS, "exp": NOW + 3600, "aud": "expected-aud", "realm_access": {"roles": ["expected-role"]}}
within_skew = {**valid, "exp": NOW - 5}
beyond_skew = {**valid, "exp": NOW - 60}
wrong_iss = {**valid, "iss": "other-iss"}
wrong_aud = {**valid, "aud": "other-aud"}
no_role = {"iss": ISS, "exp": NOW + 3600, "aud": "expected-aud"}
azp_only = {"iss": ISS, "exp": NOW + 3600, "azp": "expected-aud", "realm_access": {"roles": ["expected-role"]}}

t_valid = sign(valid)
t_within_skew = sign(within_skew)
t_beyond_skew = sign(beyond_skew)
t_wrong_iss = sign(wrong_iss)
t_wrong_aud = sign(wrong_aud)
t_no_role = sign(no_role)
t_azp_only = sign(azp_only)
t_unknown_kid = sign(valid, headers={"kid": "some-other-kid"})
t_hs256_header = make_hs256_header_token(valid)

parts = t_valid.split(".")
sig_bytes = bytearray(base64.urlsafe_b64decode(parts[2] + "=" * (-len(parts[2]) % 4)))
sig_bytes[-1] ^= 0x01
t_bad_sig = parts[0] + "." + parts[1] + "." + b64url(bytes(sig_bytes))

print("// Generated by scripts/genjwt.py against a deterministic RSA-2048 keypair.")
print(f"// Tokens use iss={ISS!r}, aud='expected-aud', role='expected-role'.")
print(f"// Frozen-now for tests: {NOW}.")
print()
print(f'pub const test_kid = "{KID}";')
print(f'pub const test_iss = "{ISS}";')
print(f"pub const test_now: i64 = {NOW};")
print(f"pub const test_modulus = {bytes_to_zig(modulus)};")
print(f"pub const test_exponent = {bytes_to_zig(exponent)};")
print()
for name, token in [
    ("token_valid", t_valid),
    ("token_within_skew", t_within_skew),
    ("token_beyond_skew", t_beyond_skew),
    ("token_wrong_iss", t_wrong_iss),
    ("token_wrong_aud", t_wrong_aud),
    ("token_no_role", t_no_role),
    ("token_azp_only", t_azp_only),
    ("token_unknown_kid", t_unknown_kid),
    ("token_hs256_header", t_hs256_header),
    ("token_bad_sig", t_bad_sig),
]:
    print(f'pub const {name}: []const u8 = "{token}";')
